### ISSUE TITLE
Error workflows pls help

### ISSUE THREAD

**Issue by orgserj** [SignTools/SignTools#137]
I only want to use the web interface for signing locally!

in the web interface, the status is always: Waiting!

> Traceback (most recent call last):
>   File "/Users/runner/work/********/********/util.py", line 27, in run_process
>     result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
>   File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '('curl', '-s', '-S', '-f', '-L', '-H', 'Authorization: ***', '-o', 'job.tar', '***/jobs')' returned non-zero exit status 7.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/runner/work/********/********/sign.py", line 348, in <module>
>     curl_with_auth(secret_url + "/jobs", output=job_archive)
>   File "/Users/runner/work/********/********/sign.py", line 27, in curl_with_auth
>     return run_process(
>   File "/Users/runner/work/********/********/util.py", line 29, in run_process
>     raise (

**Comment by ViRb3** [comment]
You are trying to use GitHub Actions, which is a remote server, and telling it to connect to localhost, which in turns points back to itself instead of your web server. That obviously won't work. If you have a macOS machine, you can set it up to become a builder using https://github.com/SignTools/SignTools-Builder. Then, you can make it local.
