### ISSUE TITLE
Screenshot Upload to https://bashupload.com

### ISSUE THREAD

**Issue by alitho24** [SignTools/SignTools#299]
I installed the advance version on my mac and everything seems to be running fine. I can access the webserver on :8080 and can create a new signing-request.

The signing request then always is in the state "waiting". I checked the debug.sh file and the program is stuck on this part:

echo "Uploading screenshot..."
until curl https://bashupload.com -T test.jpg; do
 echo "Error, sleeping"
 sleep 1
done

I found out that my web application firewall is blocking the access to https://bashupload.com and I can't get trough this filter.
I think any system without Internet-Connection will not be able to run this application. 

**System configuration**

- SignTools version: 2.6.0
- Installation type: computer
- Builder type: SignTools-Builder
- Builder version: 1.1.5

**Additional context**

I couldn't figure out what this screenshot upload is even used for. Is there a way to disable this with a parameter?

**Comment by ViRb3** [comment]
Screenshot is only uploaded if there's an error, in case the problem is with Xcode's GUI automation. Screenshots are not needed for normal use of SignTools. Check the rest of your logs and you should see the real error message. For some reason, GitHub messes up the order, so the logs may appear before or after they logically should.
